[redis]
host = "10.0.0.223:6379"
topic = "lighthouse"

[boards]
  [boards.alpha]
  serial = "/dev/ttyUSB0"
    [boards.alpha.dev]
      [boards.alpha.dev.rgb]
      mode = "rgb"
      inverted = false
      pins = ["9", "10", "11"]

      [boards.alpha.dev.internal]
      mode = "direct"
      inverted = false
      pins = ["13"]

      [boards.alpha.dev.dodec]
      mode = "pwm"
      inverted = false
      pins = ["3"]
