[redis]
host = "10.0.0.223:6379"
topic = "lighthouse"

[boards]
  [boards.alpha]
  serial = "/dev/ttyUSB0"
    [boards.alpha.dev]
      [boards.alpha.dev.stereo]
      mode = "direct"
      inverted = true
      pins = ["4", "8"]

      [boards.alpha.dev.internal]
      mode = "direct"
      inverted = false
      pins = ["13"]

      [boards.alpha.dev.dodec]
      mode = "pwm"
      inverted = false
      pins = ["11"]

      [boards.alpha.dev.input]
      mode = "servo"
      inverted = false
      pins = ["6"]
